$(document).ready(function(){
    $("#signup_div").hide();
    $("$login").click(function(){
        $("$login_div").show();
        $("#signup_div").hide();
    })
    $("#signup").click(function(){
        $("$login_div").hide();
        $("#signup_div").show();
    })
})